import { NextRequest, NextResponse } from "next/server";
import { getCachedContour, putCachedContour } from "@/lib/db";
import { ingestAuthOk } from "@/lib/ingestAuth";
import { clearWanted, ensureContour, getContourError } from "@/lib/reference";

// Spawns yt-dlp/ffmpeg + hits SQLite, so Node runtime and never static.
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// GET /api/reference?videoId=...
// Returns the song's cached pitch contour for the karaoke target line:
//   { found: true, fps, midis: number[] }       — ready (midi/frame, -1=unvoiced)
//   { found: false, status: "pending" }          — generating; poll again shortly
//   { found: false, status: "error", error }     — last attempt failed (the why)
// A miss kicks off generation in the background (deduped + backed off), so the
// next poll for a popular/queued song usually hits the cache.
export async function GET(req: NextRequest) {
  const videoId = req.nextUrl.searchParams.get("videoId")?.trim();
  if (!videoId) {
    return NextResponse.json({ error: "missing videoId" }, { status: 400 });
  }

  const cached = getCachedContour(videoId);
  if (cached) {
    return NextResponse.json({ found: true, fps: cached.fps, midis: cached.midis });
  }

  ensureContour(videoId);
  // Surface a recent failure instead of an endless "pending", so a stuck target
  // line is diagnosable (e.g. `curl …/api/reference?videoId=…`).
  const error = getContourError(videoId);
  return NextResponse.json(
    error ? { found: false, status: "error", error } : { found: false, status: "pending" }
  );
}

// POST /api/reference  { videoId, fps, midis: number[] }
// Ingest a contour generated by the off-cluster worker (see
// scripts/generate-worker.ts). Auth: `Authorization: Bearer <REFERENCE_INGEST_TOKEN>`.
export async function POST(req: NextRequest) {
  if (!ingestAuthOk(req.headers.get("authorization"))) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }
  const { videoId, fps, midis } = (body ?? {}) as {
    videoId?: unknown;
    fps?: unknown;
    midis?: unknown;
  };
  if (
    typeof videoId !== "string" ||
    !videoId ||
    typeof fps !== "number" ||
    fps <= 0 ||
    !Array.isArray(midis) ||
    midis.length === 0 ||
    midis.length > 500_000 ||
    !midis.every((m) => typeof m === "number")
  ) {
    return NextResponse.json({ error: "invalid payload" }, { status: 400 });
  }
  putCachedContour(videoId, fps, midis);
  clearWanted(videoId);
  return NextResponse.json({ ok: true, frames: midis.length });
}
